//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Planetoid_DB.Properties {
	/// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Planetoid_DB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die mpcorb.dat ähnelt.
		/// </summary>
		internal static string FilenameMpcorb
		{
			get
			{
				return ResourceManager.GetString("FilenameMpcorb", resourceCulture);
			}
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die _ ähnelt.
		/// </summary>
		internal static string FilenameMpcorbTemp
		{
			get
			{
				return ResourceManager.GetString("FilenameMpcorbTemp", resourceCulture);
			}
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die mpcorb.dat ähnelt.
		/// </summary>
		internal static string FilenameAstorb
		{
			get
			{
				return ResourceManager.GetString("FilenameAstorb", resourceCulture);
			}
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die _ ähnelt.
		/// </summary>
		internal static string FilenameAstorbTemp
		{
			get
			{
				return ResourceManager.GetString("FilenameAstorbTemp", resourceCulture);
			}
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die https://planetoid-db.de ähnelt.
		/// </summary>
		internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die info@planetoid-db.de ähnelt.
        /// </summary>
        internal static string HomepageMailExtern {
            get {
                return ResourceManager.GetString("HomepageMailExtern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mailto:info@planetoid-db.de ähnelt.
        /// </summary>
        internal static string HomepageMailIntern {
            get {
                return ResourceManager.GetString("HomepageMailIntern", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_accept {
            get {
                object obj = ResourceManager.GetObject("silk_accept", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_add {
            get {
                object obj = ResourceManager.GetObject("silk_add", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_arrow_branch {
            get {
                object obj = ResourceManager.GetObject("silk_arrow_branch", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_arrow_divide {
            get {
                object obj = ResourceManager.GetObject("silk_arrow_divide", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("silk_arrow_refresh", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_arrow_switch {
            get {
                object obj = ResourceManager.GetObject("silk_arrow_switch", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_asterisk_orange {
            get {
                object obj = ResourceManager.GetObject("silk_asterisk_orange", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_asterisk_yellow {
            get {
                object obj = ResourceManager.GetObject("silk_asterisk_yellow", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_backward_1_blue {
            get {
                object obj = ResourceManager.GetObject("silk_backward_1_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_backward_1_green {
            get {
                object obj = ResourceManager.GetObject("silk_backward_1_green", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_backward_blue {
            get {
                object obj = ResourceManager.GetObject("silk_backward_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_backward_end_blue {
            get {
                object obj = ResourceManager.GetObject("silk_backward_end_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_backward_end_green {
            get {
                object obj = ResourceManager.GetObject("silk_backward_end_green", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_backward_green {
            get {
                object obj = ResourceManager.GetObject("silk_backward_green", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_book {
            get {
                object obj = ResourceManager.GetObject("silk_book", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_bullet_arrow_down {
            get {
                object obj = ResourceManager.GetObject("silk_bullet_arrow_down", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_bullet_arrow_left {
            get {
                object obj = ResourceManager.GetObject("silk_bullet_arrow_left", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_bullet_arrow_right {
            get {
                object obj = ResourceManager.GetObject("silk_bullet_arrow_right", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_bullet_arrow_up {
            get {
                object obj = ResourceManager.GetObject("silk_bullet_arrow_up", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_bullet_goback {
            get {
                object obj = ResourceManager.GetObject("silk_bullet_goback", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_bullet_green {
            get {
                object obj = ResourceManager.GetObject("silk_bullet_green", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_calculator {
            get {
                object obj = ResourceManager.GetObject("silk_calculator", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_calendar {
            get {
                object obj = ResourceManager.GetObject("silk_calendar", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_cancel {
            get {
                object obj = ResourceManager.GetObject("silk_cancel", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_chart_bar {
            get {
                object obj = ResourceManager.GetObject("silk_chart_bar", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_chart_curve {
            get {
                object obj = ResourceManager.GetObject("silk_chart_curve", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_chart_line {
            get {
                object obj = ResourceManager.GetObject("silk_chart_line", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_chart_organisation {
            get {
                object obj = ResourceManager.GetObject("silk_chart_organisation", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_chart_pie {
            get {
                object obj = ResourceManager.GetObject("silk_chart_pie", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_clipboard {
            get {
                object obj = ResourceManager.GetObject("silk_clipboard", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_clock {
            get {
                object obj = ResourceManager.GetObject("silk_clock", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_cog {
            get {
                object obj = ResourceManager.GetObject("silk_cog", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_compress {
            get {
                object obj = ResourceManager.GetObject("silk_compress", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_computer {
            get {
                object obj = ResourceManager.GetObject("silk_computer", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_connect {
            get {
                object obj = ResourceManager.GetObject("silk_connect", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_contrast {
            get {
                object obj = ResourceManager.GetObject("silk_contrast", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_add {
            get {
                object obj = ResourceManager.GetObject("silk_control_add", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_add_blue {
            get {
                object obj = ResourceManager.GetObject("silk_control_add_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_backward {
            get {
                object obj = ResourceManager.GetObject("silk_control_backward", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_backward_1 {
            get {
                object obj = ResourceManager.GetObject("silk_control_backward_1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_backward_1_blue {
            get {
                object obj = ResourceManager.GetObject("silk_control_backward_1_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_backward_blue {
            get {
                object obj = ResourceManager.GetObject("silk_control_backward_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_backward_end {
            get {
                object obj = ResourceManager.GetObject("silk_control_backward_end", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_backward_end_blue {
            get {
                object obj = ResourceManager.GetObject("silk_control_backward_end_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_blank {
            get {
                object obj = ResourceManager.GetObject("silk_control_blank", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_blank_blue {
            get {
                object obj = ResourceManager.GetObject("silk_control_blank_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_forward {
            get {
                object obj = ResourceManager.GetObject("silk_control_forward", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_forward_1 {
            get {
                object obj = ResourceManager.GetObject("silk_control_forward_1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_forward_1_blue {
            get {
                object obj = ResourceManager.GetObject("silk_control_forward_1_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_forward_blue {
            get {
                object obj = ResourceManager.GetObject("silk_control_forward_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_forward_end {
            get {
                object obj = ResourceManager.GetObject("silk_control_forward_end", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_forward_end_blue {
            get {
                object obj = ResourceManager.GetObject("silk_control_forward_end_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_remove {
            get {
                object obj = ResourceManager.GetObject("silk_control_remove", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_remove_blue {
            get {
                object obj = ResourceManager.GetObject("silk_control_remove_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_stop {
            get {
                object obj = ResourceManager.GetObject("silk_control_stop", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_control_stop_blue {
            get {
                object obj = ResourceManager.GetObject("silk_control_stop_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_cross {
            get {
                object obj = ResourceManager.GetObject("silk_cross", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_database {
            get {
                object obj = ResourceManager.GetObject("silk_database", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_database_copy {
            get {
                object obj = ResourceManager.GetObject("silk_database_copy", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_database_lightning {
            get {
                object obj = ResourceManager.GetObject("silk_database_lightning", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_date {
            get {
                object obj = ResourceManager.GetObject("silk_date", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_decline {
            get {
                object obj = ResourceManager.GetObject("silk_decline", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_delete {
            get {
                object obj = ResourceManager.GetObject("silk_delete", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_disconnect {
            get {
                object obj = ResourceManager.GetObject("silk_disconnect", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_disk {
            get {
                object obj = ResourceManager.GetObject("silk_disk", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_door_in {
            get {
                object obj = ResourceManager.GetObject("silk_door_in", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_email {
            get {
                object obj = ResourceManager.GetObject("silk_email", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_error {
            get {
                object obj = ResourceManager.GetObject("silk_error", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_flag_de {
            get {
                object obj = ResourceManager.GetObject("silk_flag_de", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_flag_es {
            get {
                object obj = ResourceManager.GetObject("silk_flag_es", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_flag_fr {
            get {
                object obj = ResourceManager.GetObject("silk_flag_fr", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_flag_gb {
            get {
                object obj = ResourceManager.GetObject("silk_flag_gb", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_flag_it {
            get {
                object obj = ResourceManager.GetObject("silk_flag_it", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_folder {
            get {
                object obj = ResourceManager.GetObject("silk_folder", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_forward_1_blue {
            get {
                object obj = ResourceManager.GetObject("silk_forward_1_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_forward_1_green {
            get {
                object obj = ResourceManager.GetObject("silk_forward_1_green", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_forward_blue {
            get {
                object obj = ResourceManager.GetObject("silk_forward_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_forward_end_blue {
            get {
                object obj = ResourceManager.GetObject("silk_forward_end_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_forward_end_green {
            get {
                object obj = ResourceManager.GetObject("silk_forward_end_green", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_forward_green {
            get {
                object obj = ResourceManager.GetObject("silk_forward_green", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_go {
            get {
                object obj = ResourceManager.GetObject("silk_go", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_help {
            get {
                object obj = ResourceManager.GetObject("silk_help", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_hourglass {
            get {
                object obj = ResourceManager.GetObject("silk_hourglass", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_house {
            get {
                object obj = ResourceManager.GetObject("silk_house", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_image {
            get {
                object obj = ResourceManager.GetObject("silk_image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_information {
            get {
                object obj = ResourceManager.GetObject("silk_information", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_lightbulb {
            get {
                object obj = ResourceManager.GetObject("silk_lightbulb", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_lightbulb_off {
            get {
                object obj = ResourceManager.GetObject("silk_lightbulb_off", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_lightning {
            get {
                object obj = ResourceManager.GetObject("silk_lightning", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_magnifier {
            get {
                object obj = ResourceManager.GetObject("silk_magnifier", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_new {
            get {
                object obj = ResourceManager.GetObject("silk_new", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_note {
            get {
                object obj = ResourceManager.GetObject("silk_note", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_package {
            get {
                object obj = ResourceManager.GetObject("silk_package", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_package_go {
            get {
                object obj = ResourceManager.GetObject("silk_package_go", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page {
            get {
                object obj = ResourceManager.GetObject("silk_page", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page_copy {
            get {
                object obj = ResourceManager.GetObject("silk_page_copy", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page_paste {
            get {
                object obj = ResourceManager.GetObject("silk_page_paste", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page_save {
            get {
                object obj = ResourceManager.GetObject("silk_page_save", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page_white_acrobat {
            get {
                object obj = ResourceManager.GetObject("silk_page_white_acrobat", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page_white_code {
            get {
                object obj = ResourceManager.GetObject("silk_page_white_code", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page_white_compressed {
            get {
                object obj = ResourceManager.GetObject("silk_page_white_compressed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page_white_database {
            get {
                object obj = ResourceManager.GetObject("silk_page_white_database", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page_white_excel {
            get {
                object obj = ResourceManager.GetObject("silk_page_white_excel", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page_white_text {
            get {
                object obj = ResourceManager.GetObject("silk_page_white_text", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_page_white_word {
            get {
                object obj = ResourceManager.GetObject("silk_page_white_word", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_pan {
            get {
                object obj = ResourceManager.GetObject("silk_pan", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_pencil {
            get {
                object obj = ResourceManager.GetObject("silk_pencil", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_picture {
            get {
                object obj = ResourceManager.GetObject("silk_picture", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_printer {
            get {
                object obj = ResourceManager.GetObject("silk_printer", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_reload {
            get {
                object obj = ResourceManager.GetObject("silk_reload", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_report {
            get {
                object obj = ResourceManager.GetObject("silk_report", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_ruler {
            get {
                object obj = ResourceManager.GetObject("silk_ruler", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_script {
            get {
                object obj = ResourceManager.GetObject("silk_script", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_section_collapsed {
            get {
                object obj = ResourceManager.GetObject("silk_section_collapsed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_section_expanded {
            get {
                object obj = ResourceManager.GetObject("silk_section_expanded", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_style {
            get {
                object obj = ResourceManager.GetObject("silk_style", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_table {
            get {
                object obj = ResourceManager.GetObject("silk_table", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_tag {
            get {
                object obj = ResourceManager.GetObject("silk_tag", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_tag_blue {
            get {
                object obj = ResourceManager.GetObject("silk_tag_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_text_list_bullets {
            get {
                object obj = ResourceManager.GetObject("silk_text_list_bullets", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_text_list_numbers {
            get {
                object obj = ResourceManager.GetObject("silk_text_list_numbers", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_theme {
            get {
                object obj = ResourceManager.GetObject("silk_theme", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_tick {
            get {
                object obj = ResourceManager.GetObject("silk_tick", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_time {
            get {
                object obj = ResourceManager.GetObject("silk_time", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_world {
            get {
                object obj = ResourceManager.GetObject("silk_world", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_world_night {
            get {
                object obj = ResourceManager.GetObject("silk_world_night", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_wrench {
            get {
                object obj = ResourceManager.GetObject("silk_wrench", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_wrench_orange {
            get {
                object obj = ResourceManager.GetObject("silk_wrench_orange", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_zoom {
            get {
                object obj = ResourceManager.GetObject("silk_zoom", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_zoom_in {
            get {
                object obj = ResourceManager.GetObject("silk_zoom_in", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap silk_zoom_out {
            get {
                object obj = ResourceManager.GetObject("silk_zoom_out", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.minorplanetcenter.org/iau/mpc.html ähnelt.
        /// </summary>
        internal static string WebsiteMpc {
            get {
                return ResourceManager.GetString("WebsiteMpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.minorplanetcenter.org/iau/MPCORB.html ähnelt.
        /// </summary>
        internal static string WebsiteMpcorb {
            get {
                return ResourceManager.GetString("WebsiteMpcorb", resourceCulture);
            }
        }

	}
}
