//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Planetoid_DB.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("http://www.minorplanetcenter.org/iau/MPCORB/MPCORB.DAT.gz")]
        public string systemMpcorbDatGzUrl {
            get {
                return ((string)(this["systemMpcorbDatGzUrl"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string userMpcorbDatGzUrl {
            get {
                return ((string)(this["userMpcorbDatGzUrl"]));
            }
            set {
                this["userMpcorbDatGzUrl"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("http://www.minorplanetcenter.org/iau/MPCORB/MPCORB.DAT")]
        public string systemMpcorbDatUrl {
            get {
                return ((string)(this["systemMpcorbDatUrl"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string userMpcorbDatUrl {
            get {
                return ((string)(this["userMpcorbDatUrl"]));
            }
            set {
                this["userMpcorbDatUrl"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string userAstorbDatUrl {
            get {
                return ((string)(this["userAstorbDatUrl"]));
            }
            set {
                this["userAstorbDatUrl"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string userAstorbDatGzUrl {
            get {
                return ((string)(this["userAstorbDatGzUrl"]));
            }
            set {
                this["userAstorbDatGzUrl"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("https://ftp.lowell.edu/pub/elgb/astorb.dat")]
        public string systemAstorbDatUrl {
            get {
                return ((string)(this["systemAstorbDatUrl"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("https://ftp.lowell.edu/pub/elgb/astorb.dat.gz")]
        public string systemAstorbDatGzUrl {
            get {
                return ((string)(this["systemAstorbDatGzUrl"]));
            }
        }
    }
}
