//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planetoid_DB {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I10nStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I10nStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Planetoid_DB.I10nStrings", typeof(I10nStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want download the lastest MPCORB.DAT file? ähnelt.
        /// </summary>
        internal static string strAskForDownloadingLastestMpcorbDatFile {
            get {
                return ResourceManager.GetString("strAskForDownloadingLastestMpcorbDatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download MPCORB.DAT? ähnelt.
        /// </summary>
        internal static string strAskForDownloadingLastestMpcorbDatFileCaption {
            get {
                return ResourceManager.GetString("strAskForDownloadingLastestMpcorbDatFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bytes ähnelt.
        /// </summary>
        internal static string strBytesText {
            get {
                return ResourceManager.GetString("strBytesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complete ähnelt.
        /// </summary>
        internal static string strCompleteCaption {
            get {
                return ResourceManager.GetString("strCompleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copied to clipboard. ähnelt.
        /// </summary>
        internal static string strCopiedToClipboard {
            get {
                return ResourceManager.GetString("strCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading data... ähnelt.
        /// </summary>
        internal static string strDataLoading {
            get {
                return ResourceManager.GetString("strDataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download cancelled! ähnelt.
        /// </summary>
        internal static string strDownloadCancelledText {
            get {
                return ResourceManager.GetString("strDownloadCancelledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download complete! Do you want to restart the application to apply the update of the database? ähnelt.
        /// </summary>
        internal static string strDownloadCompleteAndRestartQuestionText {
            get {
                return ResourceManager.GetString("strDownloadCompleteAndRestartQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download completed! ähnelt.
        /// </summary>
        internal static string strDownloadCompleteText {
            get {
                return ResourceManager.GetString("strDownloadCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Error! ähnelt.
        /// </summary>
        internal static string strDownloadUnknownError {
            get {
                return ResourceManager.GetString("strDownloadUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string strErrorCaption {
            get {
                return ResourceManager.GetString("strErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index ähnelt.
        /// </summary>
        internal static string strIndex {
            get {
                return ResourceManager.GetString("strIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        internal static string strInformationCaption {
            get {
                return ResourceManager.GetString("strInformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MPCORB.DAT infomation ähnelt.
        /// </summary>
        internal static string strMpcorbDatInformationCaption {
            get {
                return ResourceManager.GetString("strMpcorbDatInformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MPCORB.DAT not found ähnelt.
        /// </summary>
        internal static string strMpcorbDatNotFoundCaption {
            get {
                return ResourceManager.GetString("strMpcorbDatNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file MPCORB.DAT was not found. You need it to run the application. The file has a size of about 150-200 MB. Do you want to download the MPCORB.DAT file from the MPC website? ähnelt.
        /// </summary>
        internal static string strMpcorbDatNotFoundText {
            get {
                return ResourceManager.GetString("strMpcorbDatNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no file found ähnelt.
        /// </summary>
        internal static string strNoFileFoundText {
            get {
                return ResourceManager.GetString("strNoFileFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No internet connection available! ähnelt.
        /// </summary>
        internal static string strNoInternetConnectionText {
            get {
                return ResourceManager.GetString("strNoInternetConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No update needed! ähnelt.
        /// </summary>
        internal static string strNoUpdateNeededText {
            get {
                return ResourceManager.GetString("strNoUpdateNeededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 ähnelt.
        /// </summary>
        internal static string strNumberZero {
            get {
                return ResourceManager.GetString("strNumberZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  % ähnelt.
        /// </summary>
        internal static string strPercentSign {
            get {
                return ResourceManager.GetString("strPercentSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download cancelled... ähnelt.
        /// </summary>
        internal static string strStatusDownloadCancelled {
            get {
                return ResourceManager.GetString("strStatusDownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download complete ähnelt.
        /// </summary>
        internal static string strStatusDownloadCompleteText {
            get {
                return ResourceManager.GetString("strStatusDownloadCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading... ähnelt.
        /// </summary>
        internal static string strStatusDownloading {
            get {
                return ResourceManager.GetString("strStatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nothing to do... ähnelt.
        /// </summary>
        internal static string strStatusNothingToDoText {
            get {
                return ResourceManager.GetString("strStatusNothingToDoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refreshing database... ähnelt.
        /// </summary>
        internal static string strStatusRefreshingDatabaseText {
            get {
                return ResourceManager.GetString("strStatusRefreshingDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Try to connect... ähnelt.
        /// </summary>
        internal static string strStatusTryToConnect {
            get {
                return ResourceManager.GetString("strStatusTryToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown error... ähnelt.
        /// </summary>
        internal static string strStatusUnknownError {
            get {
                return ResourceManager.GetString("strStatusUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update recommended ähnelt.
        /// </summary>
        internal static string strUpdateRecommendedText {
            get {
                return ResourceManager.GetString("strUpdateRecommendedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: {0} ähnelt.
        /// </summary>
        internal static string strVersionTemplate {
            get {
                return ResourceManager.GetString("strVersionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WWW ähnelt.
        /// </summary>
        internal static string strWww {
            get {
                return ResourceManager.GetString("strWww", resourceCulture);
            }
        }
    }
}
