//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planetoid_DB {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I10nStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I10nStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Planetoid_DB.I10nStrings", typeof(I10nStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want download the lastest MPCORB.DAT file? ähnelt.
        /// </summary>
        internal static string AskForDownloadingLastestMpcorbDatFile {
            get {
                return ResourceManager.GetString("AskForDownloadingLastestMpcorbDatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download MPCORB.DAT? ähnelt.
        /// </summary>
        internal static string AskForDownloadingLastestMpcorbDatFileCaption {
            get {
                return ResourceManager.GetString("AskForDownloadingLastestMpcorbDatFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bytes ähnelt.
        /// </summary>
        internal static string BytesText {
            get {
                return ResourceManager.GetString("BytesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complete ähnelt.
        /// </summary>
        internal static string CompleteCaption {
            get {
                return ResourceManager.GetString("CompleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copied to clipboard. ähnelt.
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading data... ähnelt.
        /// </summary>
        internal static string DataLoading {
            get {
                return ResourceManager.GetString("DataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download cancelled! ähnelt.
        /// </summary>
        internal static string DownloadCancelledText {
            get {
                return ResourceManager.GetString("DownloadCancelledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download complete! Do you want to restart the application to apply the update of the database? ähnelt.
        /// </summary>
        internal static string DownloadCompleteAndRestartQuestionText {
            get {
                return ResourceManager.GetString("DownloadCompleteAndRestartQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download completed! ähnelt.
        /// </summary>
        internal static string DownloadCompleteText {
            get {
                return ResourceManager.GetString("DownloadCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Error! ähnelt.
        /// </summary>
        internal static string DownloadUnknownError {
            get {
                return ResourceManager.GetString("DownloadUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t disturb. I&apos;m loading. ☺ ähnelt.
        /// </summary>
        internal static string EasterEgg {
            get {
                return ResourceManager.GetString("EasterEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index ähnelt.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index is out of range ähnelt.
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        internal static string InformationCaption {
            get {
                return ResourceManager.GetString("InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mail ähnelt.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MPCORB.DAT infomation ähnelt.
        /// </summary>
        internal static string MpcorbDatInformationCaption {
            get {
                return ResourceManager.GetString("MpcorbDatInformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MPCORB.DAT not found ähnelt.
        /// </summary>
        internal static string MpcorbDatNotFoundCaption {
            get {
                return ResourceManager.GetString("MpcorbDatNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file MPCORB.DAT was not found. You need it to run the application. The file has a size of about 150-200 MB. Do you want to download the MPCORB.DAT file from the MPC website? ähnelt.
        /// </summary>
        internal static string MpcorbDatNotFoundText {
            get {
                return ResourceManager.GetString("MpcorbDatNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no file found ähnelt.
        /// </summary>
        internal static string NoFileFoundText {
            get {
                return ResourceManager.GetString("NoFileFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No internet connection available! ähnelt.
        /// </summary>
        internal static string NoInternetConnectionText {
            get {
                return ResourceManager.GetString("NoInternetConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No update needed! ähnelt.
        /// </summary>
        internal static string NoUpdateNeededText {
            get {
                return ResourceManager.GetString("NoUpdateNeededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 ähnelt.
        /// </summary>
        internal static string NumberZero {
            get {
                return ResourceManager.GetString("NumberZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  % ähnelt.
        /// </summary>
        internal static string PercentSign {
            get {
                return ResourceManager.GetString("PercentSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download cancelled... ähnelt.
        /// </summary>
        internal static string StatusDownloadCancelled {
            get {
                return ResourceManager.GetString("StatusDownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download complete ähnelt.
        /// </summary>
        internal static string StatusDownloadCompleteText {
            get {
                return ResourceManager.GetString("StatusDownloadCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading... ähnelt.
        /// </summary>
        internal static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nothing to do... ähnelt.
        /// </summary>
        internal static string StatusNothingToDoText {
            get {
                return ResourceManager.GetString("StatusNothingToDoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refreshing database... ähnelt.
        /// </summary>
        internal static string StatusRefreshingDatabaseText {
            get {
                return ResourceManager.GetString("StatusRefreshingDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Try to connect... ähnelt.
        /// </summary>
        internal static string StatusTryToConnect {
            get {
                return ResourceManager.GetString("StatusTryToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown error... ähnelt.
        /// </summary>
        internal static string StatusUnknownError {
            get {
                return ResourceManager.GetString("StatusUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string strErrorCaption {
            get {
                return ResourceManager.GetString("strErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Argument of perihelion, J2000.0 (degrees)&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Argument of perihelion, J2000.0 (degrees)&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusa [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_ArgPeri {
            get {
                return ResourceManager.GetString("terminology_ArgPeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Computer name&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Computer name&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gube [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_ComputerName {
            get {
                return ResourceManager.GetString("terminology_ComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Terminology: Readable designation&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Readable designation&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_DesgnName {
            get {
                return ResourceManager.GetString("terminology_DesgnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Terminology: Epoch (in packed form, .0 TT)&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Epoch (in packed form, .0 TT)&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_Epoch {
            get {
                return ResourceManager.GetString("terminology_Epoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;4-hexdigit flags&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;4-hexdigit flags&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kas [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_Flags {
            get {
                return ResourceManager.GetString("terminology_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Inclination to the ecliptic, J2000.0 (degrees)&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Inclination to the ecliptic, J2000.0 (degrees)&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_Incl {
            get {
                return ResourceManager.GetString("terminology_Incl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Terminology: Index No.&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Index No.&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_IndexNo {
            get {
                return ResourceManager.GetString("terminology_IndexNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Longitude of the ascending node, J2000.0&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Longitude of the ascending node, J2000.0&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_LongAscNode {
            get {
                return ResourceManager.GetString("terminology_LongAscNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Absolute magnitude, H&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Absolute magnitude, H&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_MagAbs {
            get {
                return ResourceManager.GetString("terminology_MagAbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Terminology: Mean anomaly at the epoch, in degrees&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Mean anomaly at the epoch, in degrees&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et a [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_MeanAnomaly {
            get {
                return ResourceManager.GetString("terminology_MeanAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Mean daily motion (degrees per day)&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Mean daily motion (degrees per day)&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_Motion {
            get {
                return ResourceManager.GetString("terminology_Motion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Number of observations&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Number of observations&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. St [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_NumbObs {
            get {
                return ResourceManager.GetString("terminology_NumbObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Number of oppositions&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Number of oppositions&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_NumbOppos {
            get {
                return ResourceManager.GetString("terminology_NumbOppos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Date of last observation&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Date of last observation&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_ObsLastDate {
            get {
                return ResourceManager.GetString("terminology_ObsLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Observation span&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Observation span&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kas [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_ObsSpan {
            get {
                return ResourceManager.GetString("terminology_ObsSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Orbital eccentricity&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Orbital eccentricity&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet c [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_OrbEcc {
            get {
                return ResourceManager.GetString("terminology_OrbEcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Reference&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Reference&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, n [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_Ref {
            get {
                return ResourceManager.GetString("terminology_Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;r.m.s. residual (&quot;)&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;r.m.s. residual (&quot;)&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet cli [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_RmsResidual {
            get {
                return ResourceManager.GetString("terminology_RmsResidual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Semimajor axis (AU)&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Semimajor axis (AU)&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet cli [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_SemiMajorAxis {
            get {
                return ResourceManager.GetString("terminology_SemiMajorAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;Slope parameter, G&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {font-family:sans-serif;}
        ///	&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///  	&lt;h1&gt;Slope parameter, G&lt;/h1&gt;
        ///	&lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string terminology_SlopeParam {
            get {
                return ResourceManager.GetString("terminology_SlopeParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update recommended ähnelt.
        /// </summary>
        internal static string UpdateRecommendedText {
            get {
                return ResourceManager.GetString("UpdateRecommendedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: {0} ähnelt.
        /// </summary>
        internal static string VersionTemplate {
            get {
                return ResourceManager.GetString("VersionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die www ähnelt.
        /// </summary>
        internal static string Www {
            get {
                return ResourceManager.GetString("Www", resourceCulture);
            }
        }
    }
}
